spring:
  datasource:
    url: jdbc:h2:mem:camon-test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      database: 15
