package com.camon.domain.analytics.domain;

public enum AnalyticsEventName {
    ROOM_CREATED,
    PARTICIPANT_JOINED,
    READY_CHANGED,
    PARTICIPANT_DISCONNECTED,
    PARTICIPANT_RECONNECTED,
    PARTICIPANT_LEFT,
    COURSE_STARTED,
    GAME_SESSION_STARTED,
    GAME_SESSION_FINISHED,
    GAME_SESSION_SKIPPED,
    COURSE_FINISHED,
    ROOM_ENTERED,
    CAMERA_PERMISSION_RESULT,
    RECOGNITION_TEST_RESULT,
    RESULT_SCREEN_VIEWED,
    NINJA_RECOGNITION_WINDOW
}
